$baseDir = "civic-connect"

$dirs = @(
    "public/images",
    "src/assets/images",
    "src/assets/icons",
    "src/assets/illustrations",
    "src/components/common",
    "src/components/map",
    "src/components/issues",
    "src/components/dashboard",
    "src/components/forms",
    "src/components/notifications",
    "src/pages/public",
    "src/pages/auth",
    "src/pages/citizen",
    "src/pages/admin",
    "src/pages/department",
    "src/pages/officer",
    "src/pages/worker",
    "src/layouts",
    "src/context",
    "src/hooks",
    "src/services",
    "src/routes",
    "src/utils",
    "src/data"
)

foreach ($dir in $dirs) {
    $path = Join-Path $baseDir $dir
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
    }
}

$files = @(
    "public/logo.png",
    "public/favicon.ico",
    "src/components/common/Navbar.jsx",
    "src/components/common/Sidebar.jsx",
    "src/components/common/Footer.jsx",
    "src/components/common/Loading.jsx",
    "src/components/common/Modal.jsx",
    "src/components/common/Button.jsx",
    "src/components/common/Input.jsx",
    "src/components/common/Select.jsx",
    "src/components/common/ProtectedRoute.jsx",
    "src/components/map/IssueMap.jsx",
    "src/components/map/IssueMarker.jsx",
    "src/components/map/MapFilters.jsx",
    "src/components/map/LocationPicker.jsx",
    "src/components/map/HeatMap.jsx",
    "src/components/issues/IssueCard.jsx",
    "src/components/issues/IssueDetails.jsx",
    "src/components/issues/IssueStatus.jsx",
    "src/components/issues/IssueFilter.jsx",
    "src/components/issues/IssueTimeline.jsx",
    "src/components/issues/IssueImage.jsx",
    "src/components/issues/IssuePriority.jsx",
    "src/components/dashboard/StatCard.jsx",
    "src/components/dashboard/RecentIssues.jsx",
    "src/components/dashboard/ActivityFeed.jsx",
    "src/components/dashboard/AnalyticsChart.jsx",
    "src/components/dashboard/DashboardHeader.jsx",
    "src/components/forms/ReportIssueForm.jsx",
    "src/components/forms/ImageUploader.jsx",
    "src/components/forms/LocationSelector.jsx",
    "src/components/forms/DescriptionInput.jsx",
    "src/components/notifications/NotificationBell.jsx",
    "src/components/notifications/NotificationItem.jsx",
    "src/pages/public/LandingPage.jsx",
    "src/pages/public/PublicMap.jsx",
    "src/pages/public/About.jsx",
    "src/pages/public/Contact.jsx",
    "src/pages/auth/Login.jsx",
    "src/pages/auth/Register.jsx",
    "src/pages/auth/ForgotPassword.jsx",
    "src/pages/auth/ResetPassword.jsx",
    "src/pages/citizen/CitizenDashboard.jsx",
    "src/pages/citizen/ReportIssue.jsx",
    "src/pages/citizen/MyReports.jsx",
    "src/pages/citizen/NearbyIssues.jsx",
    "src/pages/citizen/IssueDetails.jsx",
    "src/pages/citizen/Notifications.jsx",
    "src/pages/citizen/Profile.jsx",
    "src/pages/admin/AdminDashboard.jsx",
    "src/pages/admin/AllIssues.jsx",
    "src/pages/admin/IssueManagement.jsx",
    "src/pages/admin/UserManagement.jsx",
    "src/pages/admin/DepartmentManagement.jsx",
    "src/pages/admin/WorkerManagement.jsx",
    "src/pages/admin/Analytics.jsx",
    "src/pages/admin/Heatmap.jsx",
    "src/pages/admin/Escalations.jsx",
    "src/pages/department/DepartmentDashboard.jsx",
    "src/pages/department/DepartmentIssues.jsx",
    "src/pages/department/AssignWorker.jsx",
    "src/pages/department/DepartmentWorkers.jsx",
    "src/pages/department/DepartmentAnalytics.jsx",
    "src/pages/officer/OfficerDashboard.jsx",
    "src/pages/officer/WardIssues.jsx",
    "src/pages/officer/WardMap.jsx",
    "src/pages/officer/WardAnalytics.jsx",
    "src/pages/worker/WorkerDashboard.jsx",
    "src/pages/worker/AssignedTasks.jsx",
    "src/pages/worker/TaskDetails.jsx",
    "src/pages/worker/UpdateTask.jsx",
    "src/pages/worker/UploadProof.jsx",
    "src/pages/worker/WorkerProfile.jsx",
    "src/layouts/PublicLayout.jsx",
    "src/layouts/AuthLayout.jsx",
    "src/layouts/CitizenLayout.jsx",
    "src/layouts/AdminLayout.jsx",
    "src/layouts/DepartmentLayout.jsx",
    "src/layouts/OfficerLayout.jsx",
    "src/layouts/WorkerLayout.jsx",
    "src/context/AuthContext.jsx",
    "src/context/IssueContext.jsx",
    "src/context/NotificationContext.jsx",
    "src/hooks/useAuth.js",
    "src/hooks/useIssues.js",
    "src/hooks/useLocation.js",
    "src/hooks/useDebounce.js",
    "src/services/api.js",
    "src/services/authService.js",
    "src/services/issueService.js",
    "src/services/userService.js",
    "src/services/departmentService.js",
    "src/services/notificationService.js",
    "src/routes/AppRoutes.jsx",
    "src/routes/CitizenRoutes.jsx",
    "src/routes/AdminRoutes.jsx",
    "src/routes/DepartmentRoutes.jsx",
    "src/routes/OfficerRoutes.jsx",
    "src/routes/WorkerRoutes.jsx",
    "src/utils/constants.js",
    "src/utils/formatDate.js",
    "src/utils/formatLocation.js",
    "src/utils/issueHelpers.js",
    "src/utils/validation.js",
    "src/data/issueCategories.js",
    "src/data/mockIssues.js",
    "src/data/mockUsers.js"
)

foreach ($file in $files) {
    $path = Join-Path $baseDir $file
    if (-not (Test-Path $path)) {
        New-Item -ItemType File -Path $path -Force | Out-Null
        
        # Add basic imports and export for jsx and js files to avoid complete emptiness (optional, but requested "do not add any code")
        # Since user said "do not add any code", I will leave them perfectly empty as created by New-Item.
    }
}
